[terminal.shell]

program = "/usr/bin/fish"

[general]
import  = ["~/.config/alacritty/omni.toml"]

[terminal]
#builtin_box_drawing   = true
[font]
size = 12

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

[font.bold]
family = "Hack Nerd Font"
style = "Bold"

[font.italic]
family = "Hack Nerd Font"
style = "Italic"
