unbind r
bind r source-file ~/.tmux.conf
set -g mouse on
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R
# trocar de window com Ctrl + ← →
bind -n C-h select-pane -L
bind -n C-l select-pane -R
bind -n C-j select-pane -D
bind -n C-k select-pane -U
set -g @plugin "tmux-plugins/tpm"
bind -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "xclip -selection clipboard"
# configura o shell
set -g default-shell /usr/bin/fish
set -g default-command /usr/bin/fish
run "~/.tmux/plugins/tpm/tpm"
